# Build stage
FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

# Production stage
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server .

EXPOSE 5001

CMD ["./server"]
