# Listening ports
listening-port=3478
tls-port=5349

# IP Konfigurasi untuk Jaringan NAT Kosan/Provider
listening-ip=0.0.0.0
external-ip=182.253.158.158

# Protokol Keamanan & Auth
fingerprint
lt-cred-mech
no-tlsv1
no-tlsv1_1

# User authentication untuk FunFram (Disamakan dengan .env kamu)
user=funfram:letsgooo_Funfram
realm=funfram.roomify.space

# Alokasi Port Dynamic untuk Streaming Video/Suara
min-port=49152
max-port=65535

# Logging
log-file=stdout
no-stdout-log
no-cli